site:
  baseUrl: "https://codgician.me"
  title:
    en: "codgician"
  subtitle:
    en: "Coding Magic"
  typewriterPhrases:
    en:
      - "Coding Magic"
      - "Vibing..."
  copyright:
    en: "© 2026 codgician"
languages:
  - code: en
    label: English
  - code: zh
    label: 中文
author:
  name: "codgician"
  email: "codgician@outlook.com"
navigation:
  - url: posts/
    label:
      en: Blog
      zh: 博客
  - url: about/
    label:
      en: About
      zh: 关于
social:
  - url: "https://github.com/codgician"
    icon: github
    label:
      en: GitHub
  - url: "https://x.com/codgician"
    icon: twitter
    label:
      en: X
  - url: "https://t.me/codgician"
    icon: send
    label:
      en: Telegram
feed:
  itemsCount: 20
  title:
    en: "codgician's Blog"
    zh: "codgician 的博客"
  description:
    en: "Coding Magic"
