site:
  baseUrl: "https://codgician.me"
  title:
    en: "codgician"
  subtitle:
    en: "Coding Magic"
  typewriterPhrases:
    en:
      - "Coding Magic"
      - "Vibing..."
      - "INFP-T?"
      - "nix build ."
      - "原神，启动！"
      - "忆伊时，吾亦思"
  copyright:
    en: "© 2026 codgician"
  license:
    name: "CC BY-NC-SA 4.0"
    url: "https://creativecommons.org/licenses/by-nc-sa/4.0/"
languages:
  - code: en
    label: English
  - code: zh
    label: 中文
author:
  name: "codgician"
navigation:
  - url: posts/
    label:
      en: Blog
      zh: 博客
  - url: slides/
    label:
      en: Slides
      zh: 幻灯片
  - url: about/
    label:
      en: About
      zh: 关于
social:
  - url: "https://github.com/codgician"
    icon: github
    label:
      en: GitHub
  - url: "https://x.com/codgician"
    icon: twitter
    label:
      en: X
  - url: "https://t.me/codgician"
    icon: send
    label:
      en: Telegram
  - url: "https://www.linkedin.com/in/codgician"
    icon: linkedin
    label:
      en: LinkedIn
friends:
  - name: "Anduin Xue"
    url: "https://anduin.aiursoft.com"
  - name: "Ziqiao Ma"
    url: "https://mars-tin.github.io/"
  - name: "fstqwq"
    url: "http://fstqwq.pw/"
  - name: "t123yh"
    url: "https://blog.t123yh.xyz:2/"
  - name: "ice1000"
    url: "https://ice1000.org/"
  - name: "HPLV"
    url: "https://hplv.github.io/"
  - name: "Nota"
    url: "https://nota.moe/"
  - name: "cxhscst2"
    url: "https://www.cnblogs.com/cxhscst2/"
  - name: "Hanano"
    url: "https://hanano-yuuki.github.io/"
  - name: "Reminiscent"
    url: "https://www.cnblogs.com/HDUjackyan/"
  - name: "Changer-qyz"
    url: "https://www.cnblogs.com/changer-qyz/"
  - name: "Li4n0"
    url: "https://0n0.fun/"
  - name: "K0u1e"
    url: "https://blog.nowcoder.net/wcyctmd"
  - name: "syh0313"
    url: "https://blog.csdn.net/syh0313"
  - name: "Zarxdy34"
    url: "http://www.zarxdy34.top/"
  - name: "BinGoo0o0o"
    url: "https://blog.csdn.net/BinGoo0o0o/"
  - name: "whdsunny"
    url: "https://www.cnblogs.com/whdsunny/"
feed:
  itemsCount: 20
  title:
    en: "codgician's Blog"
    zh: "codgician 的博客"
  description:
    en: "Coding Magic"
pagination:
  posts:
    itemsPerPage: 20
  slides:
    itemsPerPage: 24
