site:
  baseUrl: "https://codgician.me"
  title:
    en: "codgician"
    zh: "codgician"
  subtitle:
    en: "Coding Magic"
    zh: "编码魔法"
  copyright:
    en: "© 2025 codgician"
    zh: "© 2025 codgician"
languages:
  - code: en
    label: English
  - code: zh
    label: 中文
author:
  name: "codgician"
  email: "codgician@outlook.com"
navigation:
  - url: posts/
    label:
      en: Blog
      zh: 博客
  - url: about/
    label:
      en: About
      zh: 关于
social:
  - url: "https://github.com/codgician"
    icon: github
    label:
      en: GitHub
      zh: GitHub
  - url: "mailto:codgician@outlook.com"
    icon: mail
    label:
      en: Email
      zh: 邮箱
feed:
  itemsCount: 20
  title:
    en: "codgician's Blog"
    zh: "codgician 的博客"
  description:
    en: "Coding Magic"
    zh: "编码魔法"
